// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA61Mq_-DnvM6YqYplc3F7QRhxxYp7Cv4',
    appId: '1:645716803839:web:adb6df906d495e8f634cca',
    messagingSenderId: '645716803839',
    projectId: 'flutter-chatapp-9ae1b',
    authDomain: 'flutter-chatapp-9ae1b.firebaseapp.com',
    databaseURL: 'https://flutter-chatapp-9ae1b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chatapp-9ae1b.appspot.com',
    measurementId: 'G-PZZBNL4JNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xwa4r2PQW3jwIDl9GOtsDrIcKohpNWQ',
    appId: '1:645716803839:android:d073dacb4beea317634cca',
    messagingSenderId: '645716803839',
    projectId: 'flutter-chatapp-9ae1b',
    databaseURL: 'https://flutter-chatapp-9ae1b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chatapp-9ae1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPelp6ivPe74tTsjgSFot3QwaEqMaqMAI',
    appId: '1:645716803839:ios:16a33e1e87f19cee634cca',
    messagingSenderId: '645716803839',
    projectId: 'flutter-chatapp-9ae1b',
    databaseURL: 'https://flutter-chatapp-9ae1b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chatapp-9ae1b.appspot.com',
    iosClientId: '645716803839-lc1ajgb9p1l83rmmea4ijn0b2ut3c1vf.apps.googleusercontent.com',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPelp6ivPe74tTsjgSFot3QwaEqMaqMAI',
    appId: '1:645716803839:ios:90f58ffed2bc15cf634cca',
    messagingSenderId: '645716803839',
    projectId: 'flutter-chatapp-9ae1b',
    databaseURL: 'https://flutter-chatapp-9ae1b-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chatapp-9ae1b.appspot.com',
    iosClientId: '645716803839-3r31kmu9h2fhgkcepu7so576lnkv63gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatapp',
  );
}
